title: 'blackmida0x.github.io'
description: "Tech hub"
baseurl: "/web_blog"
url: "https://blackmida0x.github.io"

header_pages:
  - index.md
  - lab.md
  #- about.md
  #- contact.md


style: dark

footer: '<a href="https://twitter.com/">twitter</a> | <a href="https://twitter.com/">Github</a> | <a href="https://twitter.com/">Mirror</a>'

# Build settings
markdown: kramdown
#remote_theme: b2a3e8/jekyll-theme-console
