title: 'blackmida0x.github.io'
description: "Tech hub"
baseurl: "/web_blog"
url: "https://blackmida0x.github.io"

header_pages:
  - index.md
  - lab.md
  #- about.md
  #- contact.md

paginate: 5
paginate_path: "/page:num/"


style: dark

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
#remote_theme: b2a3e8/jekyll-theme-console
